#!/bin/bash

echo "Running mvn checkstyle:check..."

cd chapter7/crm-backend && mvn checkstyle:check

if [ $? -ne 0 ]; then
    echo "Checkstyle check failed. Please fix the issues before committing."
    exit 1
fi

echo "Checkstyle check passed."
exit 0
